version: 1

enable:
  - "GO-*"
  - "PY-*"

overrides:
  GO-CONC-001:
    severity: warning

path_policies:
  - match: "**/vendor/**"
    override:
      disable_all: true
  - match: "**/generated/**"
    override:
      disable_all: true
  - match: "**/*_test.go"
    override:
      severity_floor: info